
IF NOT EXISTS
(
    SELECT *
    FROM sys.availability_groups
    WHERE name = 'ag1'
)
    BEGIN
	ALTER AVAILABILITY GROUP [ag1] JOIN WITH (CLUSTER_TYPE = EXTERNAL);
    ALTER AVAILABILITY GROUP [ag1] GRANT CREATE ANY DATABASE;

END;
