
IF NOT EXISTS
(
    SELECT *
    FROM sys.availability_groups
    WHERE name = 'ag1'
)
    BEGIN
	ALTER AVAILABILITY GROUP [ag1] JOIN WITH (CLUSTER_TYPE = NONE);
        ALTER AVAILABILITY GROUP [ag1] GRANT CREATE ANY DATABASE;
	ALTER AVAILABILITY GROUP AG1 SET (HEALTH_CHECK_TIMEOUT =60000);

END;
